train_file: "data/processed/text2rdf.train.jsonl"
val_file: "data/processed/text2rdf.val.jsonl"
tokenizer_file: "data/vocab/bpe.json"

# modello
d_model: 384
nhead: 6
enc_layers: 3
dec_layers: 3
ff_dim: 1536
dropout: 0.1
max_len: 256

# training
batch_size: 16
lr: 3e-4
weight_decay: 0.01
warmup_steps: 2000
max_steps: 30000
eval_every: 1000
save_dir: "checkpoints/baseline"
seed: 42

device: "cuda"        # oppure "cpu"
num_workers: 4
